- hosts: main
  strategy: free
  tasks:
    - name: Install decoder service description file
      become: true
      copy:
        src: decoder.service
        dest: /etc/avahi/services
    - name: Reload avahi-daemon
      become: true
      service:
        name: avahi-daemon.service
        state: restarted
    - name: Sync model alphabet onto system
      synchronize:
        src: ./models/alphabet.txt
        dest: /home/pi/models
    - name: Sync model graph onto system
      synchronize:
        src: ./models/output_graph.pb
        dest: /home/pi/models
    - name: Clone repo onto system
      synchronize:
        recursive: yes
        src: ./
        dest: /home/pi/project
    - name: Install decoder service file
      become: true
      copy:
        src: deepspeech-server.service
        dest: /etc/systemd/system/

