- hosts: main
  vars:
    ansible_user: pi
    #strategy: free
  tasks:
    - name: Install decoder service description file
      become: true
      copy:
        src: decoder.service
        dest: /etc/avahi/services
    - name: Reload avahi-daemon
      become: true
      service:
        name: avahi-daemon.service
        state: restarted
    - name: Create model directory
      file:
        state: directory
        path: /home/pi/models
    - name: Sync model alphabet onto system
      synchronize:
        src: ./models/alphabet.txt
        dest: /home/pi/models/alphabet.txt
    - name: Sync model graph onto system
      synchronize:
        src: ./models/output_graph.pb
        dest: /home/pi/models/output_graph.pb
    - name: Install git
      become: true
      apt:
        update_cache: true
        name: git
    - name: Clone repo onto system
      git:
        repo: https://github.com/andyg0808/deepspeech-server.git
        dest: /home/pi/project
    - name: Copy native client to pi
      synchronize:
        recursive: yes
        src: ./native
        dest: /home/pi/project
    - name: Install decoder service file
      become: true
      copy:
        src: deepspeech-server.service
        dest: /etc/systemd/system/
    - name: Install sox for deepspeech
      become: true
      apt:
        name: sox
    - name: Install libsox2 for deepspeech
      become: true
      apt:
        name: libsox2
    - name: Install pip
      become: true
      apt:
        name: python3-pip
    - name: Install pipenv
      become: true
      pip:
        executable: pip3
        name: pipenv
    - name: Install other needed components
      become: true
      args:
        chdir: /home/pi/project
      command: pipenv install --system --skip-lock
      # We have to ignore the Pipfile.lock for this, because it's got hashes
      # for x86_64 packages in it, and the ARM packages have different hashes.

    - name: Check if swapfile exists
      # See https://stackoverflow.com/a/35680071/2243495
      become: true
      stat:
        path: /swapfile
      register: swapfile_stat
    - name: Create swapfile
      become: true
      command: dd if=/dev/zero of=/swapfile bs=500M count=1
      when: swapfile_stat.stat.exists == False
    - name: Set permissions of swapfile
      become: true
      file:
        path: /swapfile
        mode: 0600
    - name: Format swapfile
      become: true
      command: mkswap /swapfile
      when: swapfile_stat.stat.exists == False
    - name: Activate swap in fstab
      become: true
      lineinfile:
        path: /etc/fstab
        regexp: /swapfile
        line: /swapfile swap swap defaults
    - name: Mount swap
      become: true
      command: swapon -a

    - name: Start decoder service
      become: true
      service:
        name: deepspeech-server.service
        state: started
        enabled: yes
