- hosts: localhost
  tasks:
    - name: Clear out old keys for ip
      command: "ssh-keygen -R {{hostvars[host].ip}}"
    - name: Clear out old keys for hostname
      command: "ssh-keygen -R {{host}}"
    - name: Add key to authorized_keys on default system
      command: "ssh-copy-id pi@{{hostvars[host].ip}}"
- hosts: "{{host}}"
  vars_files:
    - ./vault.yml
  become: true
  vars:
    ansible_host: "{{ip}}"
    ansible_user: pi
  tasks:
    - name: Enable en_US.UTF-8
      lineinfile:
        path: /etc/locale.gen
        regexp: en_US.UTF-8
        line: en_US.UTF-8 UTF-8
    - name: Generate localization files
      command: locale-gen
    - name: Update locale config
      command: update-locale en_US.UTF-8
    - name: Set hostname
      hostname: 
        name: "{{inventory_hostname_short}}"
    - name: Add avahi-daemon
      apt:
        update_cache: yes
        name: avahi-daemon
    - name: Expose system via zeroconf
      lineinfile:
        path: /etc/avahi/avahi-daemon.conf
        regexp: publish-workstation
        line: publish-workstation=yes
        #    - name: Allow avahi-daemon to run despite .local
        #      lineinfile:
        #        path: /etc/default/avahi-daemon

    - name: Reload avahi-daemon
      service:
        name: avahi-daemon.service
        state: restarted
    - name: Set standard password for user
      user:
        name: pi
        password: "{{password | password_hash('sha256')}}"
    - name: Copy DNS server config for ethernet
      command: echo "nameserver 8.8.8.8" | resolvconf -a eth0
    - name: Copy DNS server config for wifi
      command: echo "nameserver 8.8.8.8" | resolvconf -a wlan0
