# Commands in this file based on
# https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md
- hosts: "{{host}}"
  vars:
    ansible_user: pi
  vars_files:
    - ./wifi.yml
  become: true
  tasks:
    - name: Get wpa_passphrase version of provided passphrase
      shell: "echo '{{wifi_password}}' | wpa_passphrase '{{wifi_ssid}}'"
      register: wpa_network_config
    - name: Setup wpa_supplicant.conf
      template:
        src: wpa_supplicant.conf
        dest: /etc/wpa_supplicant/wpa_supplicant.conf
    - name: Reconfigure wifi interface
      command: wpa_cli -i wlan0 reconfigure
